name: Actions Tester

on: 
  push:
  workflow_dispatch: 

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['8', '10', '12']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Check out my other private repo
      uses: actions/checkout@v2
      with:
        repository: rfennell/SampleRepo
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
    - uses: rfennell/JSONFileVersioner@v1
      with:
        path: 'testdata'
        field: 'version'
        VersionNumber: '1.2.3'
        filenamepattern: '.json' 
        recursion: 'true'
      env:
        CI: true

  ReleaseNotes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: rfennell/ReleaseNotesAction@v1
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
         templateFile: '${{ github.workspace }}/template.md'
         outputfile: '${{ github.workspace }}/releasenotes.md'
         extensionsfile: '${{ github.workspace }}/customextensions.js'
    - name: Archive Release Notes
      uses: actions/upload-artifact@v2
      with:
        name: ReleaseNotes
        path: |
          ./releasenotes.md   
