name: Node CI

on: [push]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      matrix:
        node_version: [8, 10, 12]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: rfennell/JSONFileVersioner@v1
      with:
        path: 'testdata'
        field: 'version'
        VersionNumber: '1.2.3'
        filenamepattern: '.json' 
        recursion: 'true'
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm test
      env:
        CI: true
